### ISSUE TITLE
README should use tslint.json in Settings example

### ISSUE THREAD

**Issue by alshamma** [lavrton/SublimeLinter-contrib-tslint#13]
The README uses an example that contains:
            "config_filename": "tsconfig.json"

I think this is confusing because my project (which I've just started working on) already has a tsconfig.json for another purpose. Would be more clear if the example referred to tslint.json. 

Thanks.

**Comment by LJNielsenDk** [comment]
Same here. I just spent an hour trying to get it to work on the assumption that it used the location of tsconfig.json to figure out where the project root was. Found this issue when I was about to report it myself.
