### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by itajaja** [lavrton/SublimeLinter-contrib-tslint#17]
seems like the latest release for package manager is [very old](https://github.com/lavrton/SublimeLinter-contrib-tslint/blob/1.1.0/linter.py). For example, it still subclasses Linter, and not NodeLinter. Could you cut and publish a new release?
Thanks!

**Comment by lavrton** [comment]
Done. Please try it.

**Comment by itajaja** [comment]
perfect, it works! no need to install tslint globally anymore :)

**Comment by olivierdalang** [comment]
Hi,

I don't see SublimeLinter-contrib-tslint in package manager list at all ? Is it only here ?

Thanks !
