### ISSUE TITLE
config file default location

### ISSUE THREAD

**Issue by madreason** [lavrton/SublimeLinter-contrib-tslint#2]
Please, change line with [config-file](http://www.sublimelinter.com/en/latest/linter_attributes.html#config-file)
> config_file = ('--config', 'tslint.json')

to 
> config_file = ('--config', 'tslint.json', '~')

The file will be searched in the project directory. Otherwise the plugin can't find the file by default path and crashes without any message.

**Comment by lavrton** [comment]
Done. Thanks.
