### ISSUE TITLE
Make the linter run `yarn tslint` instead of just `tslint`

### ISSUE THREAD

**Issue by burlesona** [lavrton/SublimeLinter-contrib-tslint#27]
I have tslint globally installed but due to the way my projects are set up it doesn't really work correctly to run `tslint` directly, rather I always run `yarn tslint` which works as expected.

I've poked around all the docs on SublimeLinter and this plugin, and as far as I can tell the `tslint` command is hardcoded into the plugin. Is there any way to specify to run `yarn tslint` instead?

**Comment by kaste** [comment]
Something like this is possible in SL4, you need to set 'executable' to ['yarn', 'tslint'] in the linter settings.

**Comment by burlesona** [comment]
Thanks for the help @kaste. This seems to work. I'm having another problem but it looks like others are tracking the same issue here (#28) so I'll chime in on that thread. Thanks!
