### ISSUE TITLE
TsLint no longer supports -f option

### ISSUE THREAD

**Issue by jramoyo** [lavrton/SublimeLinter-contrib-tslint#3]
With the current version of tslint (2.4.2), the -f option is no longer supported. This causes the linter to fail with the following message:

    SublimeLinter: tslint: some-file.ts ['/usr/bin/tslint', '-f', '@', '--config', '/home/user/some_dir/tslint.json'] 
    SublimeLinter: tslint output:
    usage: node /usr/bin/tslint

    Options:
      -c, --config          configuration file                  
      -h, --help            display detailed help               
      -o, --out             output file                         
      -r, --rules-dir       rules directory                     
      -s, --formatters-dir  formatters directory                
      -t, --format          output format (prose, json, verbose)  [default: "prose"]
      -v, --version         current version                     

    Missing files

**Comment by lavrton** [comment]
Should be fixed now. Thanks for report.

**Comment by jramoyo** [comment]
Thanks! How do I get the latest version from Package Control?

**Comment by lavrton** [comment]
I am not sure how often Package Control check repo. I guess during a day update will be available.
