### ISSUE TITLE
Do we need to install tslint globally?

### ISSUE THREAD

**Issue by yangmillstheory** [lavrton/SublimeLinter-contrib-tslint#7]
Great plugin; using it now.

I'm wondering if we need to install `tslint` globally, as it says in the docs. I often install it on a per-project basis and don't want to maintain a global copy.

I think I can configure the path to the executable, but I'm still new to the Sublime Text ecosystem so I was having some problems with that, or I'm misunderstanding something. Would you happen to know if this is possible?

Secondly, would it make sense to for the plugin to prefer `./node_modules/.bin/tslint`, and use only the global executable if that fails?

**Comment by lavrton** [comment]
Actually it should work with local install too. Try it.

**Comment by yangmillstheory** [comment]
Thanks for the reply.

What's the best way to configure this?

```shell
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Applications/Sublime Text.app/Contents/MacOS/${project}/node_modules/.bin
/Library/Frameworks/Python.framework/Versions/3.5/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/Frameworks/Python.framework/Versions/3.5/bin
 
SublimeLinter: WARNING: tslint deactivated, cannot locate 'tslint' 
```

**Comment by yangmillstheory** [comment]
I used this approach in `SublimeLinter.sublime-settings`:

```javascript
...
"paths": {
    "*": [],
    "linux": [],
    "osx": [
        "~/code/private/node/node_modules/.bin"
    ],
    "windows": []
},  
...
```
